# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 14:30
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0051_auto_20170205_1407'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitinglistentry',
            options={'ordering': ['created'], 'verbose_name': 'Waiting list entry', 'verbose_name_plural': 'Waiting list entries'},
        ),
        migrations.AlterField(
            model_name='waitinglistentry',
            name='voucher',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Voucher', verbose_name='Assigned voucher'),
        ),
    ]
