# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 21:50
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0052_auto_20170205_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='waitinglistentry',
            name='locale',
            field=models.CharField(default='en', max_length=190),
        ),
        migrations.AlterField(
            model_name='cachedcombinedticket',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='waitinglistentry',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pretixbase.Voucher', verbose_name='Assigned voucher'),
        ),
    ]
